In [1]:
import pymongo
import pandas as pd
import re
import numpy as np

In [2]:
user = 'team04'
pw = '1111'
host = 'ec2-54-95-8-243.ap-northeast-1.compute.amazonaws.com'
client = pymongo.MongoClient(f'mongodb://{user}:{pw}@{host}:27017/')
db = client.resell

In [3]:
df = pd.DataFrame(db.kream_detail.find())
df[['_id']].head()

                                                 _id
0                          Jordan 1 Low Vintage Grey
1  Jordan 1 x Travis Scott x Fragment Retro Low O...
2                 Jordan 1 Retro High OG Black Mocha
3                     Jordan 4 Retro White and Black
4              Jordan 1 Retro High OG Bleached Coral

In [4]:
def extract_collabo(data):
    p = re.compile(r"\bx\s\w+", re.M)
    result = p.findall(data)
    
    result = [word[2:] for word in result]
    
    return ','.join(result)

In [5]:
df['collabo'] = df['_id'].apply(extract_collabo)

In [6]:
df1 = df[df['collabo'] != ''][['_id', 'collabo']]
df1.iloc[:50]

                                                   _id          collabo
1    Jordan 1 x Travis Scott x Fragment Retro Low O...  Travis,Fragment
19   Jordan 1 x A Ma Maniere Retro High OG SP Sail ...                A
39      Jordan 1 x Travis Scott Retro High OG SP Mocha           Travis
56       Jordan 1 x Travis Scott Retro Low OG SP Mocha           Travis
68      Jordan 6 x Travis Scott Retro SP British Khaki           Travis
84                  Jordan 2 x Union Retro SP Grey Fog            Union
99                   Jordan 1 x J Balvin Retro High OG                J
102  Jordan 2 x Maison Chateau Rouge Retro SP Orang...           Maison
119   Jordan Series x Maison Chateau Rouge Mid SP Sail           Maison
127              Jordan 4 x Union Retro SP Desert Moss            Union
130  Jordan 2 x Off-White Retro Low SP White and Va...              Off
131                    Jordan 4 x Union Retro Off Noir            Union
133           Jordan 3 x Fragment Retro SP White Black         Fragment
135                Jordan 6 x Travis Scott Retro Olive           Travis
137        Jordan 5 x Off-White Retro SP Sail Fire Red              Off
138              Jordan 1 x Union Retro High Black Toe            Union
141    Jordan 1 x Off-White Retro High University Blue              Off
144               Jordan 1 x Union Retro High Blue Toe            Union
148    Jordan 1 x Trophy Room Retro High OG SP Chicago           Trophy
150                             Jordan 1 x Dior Low OG             Dior
158  (W) Jordan 2 x Nina Chanel Abney Retro Low SE ...             Nina
165                  Jordan 1 x Fragment Retro High OG         Fragment
209  Jordan 1 x League of Legends Zoom Air CMFT Esp...           League
221       (W) Jordan 15 x Billie Eilish Retro SP Beige           Billie
276  (TD) Jordan 1 x A Ma Maniere Retro High OG SP ...                A
287            Jordan 5 x Clot Retro Low SP Anthracite             Clot
289  Jordan 1 x Travis Scott x Fragment Retro High ...  Travis,Fragment
293  Jordan 2 x Off-White Retro Low SP Black and Va...              Off
303  Jordan 2 x A Ma Maniere Retro SP Sail and Burg...                A
307  Jordan 1 x SoleFly Retro Low OG SP Black and S...          SoleFly
311       Jordan 1 x Paris Saint-Germain Zoom Air CMFT            Paris
315      (W) Jordan 1 x Billie Eilish KO SP Lime Green           Billie
317               (W) Jordan 3 x A Ma Maniere Retro SP                A
324                   Jordan 2 x Union Retro SP Rattan            Union
327         Jordan 5 x Off-White Retro SP Black Muslin              Off
343             (W) Jordan 4 x Off-White Retro SP Sail              Off
344            Jordan x Union Crater Slide SP Grey Fog            Union
355                   Jordan 4 x Union Retro Guava Ice            Union
358     (W) Jordan 1 x Aleali May Zoom CMFT SP Califia           Aleali
372  Jordan x Russell Westbrook Honor the Gift Why ...          Russell
379  (PS) Jordan 1 x A Ma Maniere Retro High OG SP ...                A
410                            Jordan 1 x Dior High OG             Dior
435    Jordan 1 x Off-White Retro High Chicago The Ten              Off
445          Jordan 4 x Travis Scott Retro Cactus Jack           Travis
460               Jordan 7 x Paris Saint-Germain Retro            Paris
477  (PS) Jordan 2 x Maison Chateau Rouge Retro SP ...           Maison
480              Jordan 14 x Clot Retro Low Terracotta             Clot
507    Jordan 1 x Maison Chateau Rouge Mid SE Fearless           Maison
516                  Jordan x Union Delta Mid Off Noir            Union
561     Jordan 1 x Lance Mountain Low SB QS Desert Ore            Lance

In [7]:
df1[df1['_id'].apply(lambda x: 'x' in x)][['_id', 'collabo']].head(50)

                                                   _id          collabo
1    Jordan 1 x Travis Scott x Fragment Retro Low O...  Travis,Fragment
19   Jordan 1 x A Ma Maniere Retro High OG SP Sail ...                A
39      Jordan 1 x Travis Scott Retro High OG SP Mocha           Travis
56       Jordan 1 x Travis Scott Retro Low OG SP Mocha           Travis
68      Jordan 6 x Travis Scott Retro SP British Khaki           Travis
84                  Jordan 2 x Union Retro SP Grey Fog            Union
99                   Jordan 1 x J Balvin Retro High OG                J
102  Jordan 2 x Maison Chateau Rouge Retro SP Orang...           Maison
119   Jordan Series x Maison Chateau Rouge Mid SP Sail           Maison
127              Jordan 4 x Union Retro SP Desert Moss            Union
130  Jordan 2 x Off-White Retro Low SP White and Va...              Off
131                    Jordan 4 x Union Retro Off Noir            Union
133           Jordan 3 x Fragment Retro SP White Black         Fragment
135                Jordan 6 x Travis Scott Retro Olive           Travis
137        Jordan 5 x Off-White Retro SP Sail Fire Red              Off
138              Jordan 1 x Union Retro High Black Toe            Union
141    Jordan 1 x Off-White Retro High University Blue              Off
144               Jordan 1 x Union Retro High Blue Toe            Union
148    Jordan 1 x Trophy Room Retro High OG SP Chicago           Trophy
150                             Jordan 1 x Dior Low OG             Dior
158  (W) Jordan 2 x Nina Chanel Abney Retro Low SE ...             Nina
165                  Jordan 1 x Fragment Retro High OG         Fragment
209  Jordan 1 x League of Legends Zoom Air CMFT Esp...           League
221       (W) Jordan 15 x Billie Eilish Retro SP Beige           Billie
276  (TD) Jordan 1 x A Ma Maniere Retro High OG SP ...                A
287            Jordan 5 x Clot Retro Low SP Anthracite             Clot
289  Jordan 1 x Travis Scott x Fragment Retro High ...  Travis,Fragment
293  Jordan 2 x Off-White Retro Low SP Black and Va...              Off
303  Jordan 2 x A Ma Maniere Retro SP Sail and Burg...                A
307  Jordan 1 x SoleFly Retro Low OG SP Black and S...          SoleFly
311       Jordan 1 x Paris Saint-Germain Zoom Air CMFT            Paris
315      (W) Jordan 1 x Billie Eilish KO SP Lime Green           Billie
317               (W) Jordan 3 x A Ma Maniere Retro SP                A
324                   Jordan 2 x Union Retro SP Rattan            Union
327         Jordan 5 x Off-White Retro SP Black Muslin              Off
343             (W) Jordan 4 x Off-White Retro SP Sail              Off
344            Jordan x Union Crater Slide SP Grey Fog            Union
355                   Jordan 4 x Union Retro Guava Ice            Union
358     (W) Jordan 1 x Aleali May Zoom CMFT SP Califia           Aleali
372  Jordan x Russell Westbrook Honor the Gift Why ...          Russell
379  (PS) Jordan 1 x A Ma Maniere Retro High OG SP ...                A
410                            Jordan 1 x Dior High OG             Dior
435    Jordan 1 x Off-White Retro High Chicago The Ten              Off
445          Jordan 4 x Travis Scott Retro Cactus Jack           Travis
460               Jordan 7 x Paris Saint-Germain Retro            Paris
477  (PS) Jordan 2 x Maison Chateau Rouge Retro SP ...           Maison
480              Jordan 14 x Clot Retro Low Terracotta             Clot
507    Jordan 1 x Maison Chateau Rouge Mid SE Fearless           Maison
516                  Jordan x Union Delta Mid Off Noir            Union
561     Jordan 1 x Lance Mountain Low SB QS Desert Ore            Lance

In [8]:
c = 'Clot,Fragment,Union,Jayson_Tatum,J_Balvin,League_of_Legends,Paris_Saint_Germain,A_Ma_Maniere,Trophy_Room,Travis_Scott,Maison_Chateau_Rouge,Dior,Nina_Chanel_Abney,Billie_Eilish,Off_White,SoleFly,Russell_Westbrook,Supreme,Levis,Patta,Aleali_May,Social_Status,Ghetto_Gastro,Blue_The_Great,Lance_Mountain,SNS,Facetasm,DSM,Kaws,Olivia_Kim,Titan,Melody_Ehsani,Anna_Wintour,Converse,Vogue,Serena_Williams,Carmelo_Anthony,Carhartt,Sheila_Rashid,Pendleton,Rox_Brown,Nike,Comme_des_Garcons_Homme,PSNY'
collabo_lst = c.split(',')
collabo_lst = [collabo.replace('_', ' ') for collabo in collabo_lst]
collabo_lst

['Clot',
 'Fragment',
 'Union',
 'Jayson Tatum',
 'J Balvin',
 'League of Legends',
 'Paris Saint Germain',
 'A Ma Maniere',
 'Trophy Room',
 'Travis Scott',
 'Maison Chateau Rouge',
 'Dior',
 'Nina Chanel Abney',
 'Billie Eilish',
 'Off White',
 'SoleFly',
 'Russell Westbrook',
 'Supreme',
 'Levis',
 'Patta',
 'Aleali May',
 'Social Status',
 'Ghetto Gastro',
 'Blue The Great',
 'Lance Mountain',
 'SNS',
 'Facetasm',
 'DSM',
 'Kaws',
 'Olivia Kim',
 'Titan',
 'Melody Ehsani',
 'Anna Wintour',
 'Converse',
 'Vogue',
 'Serena Williams',
 'Carmelo Anthony',
 'Carhartt',
 'Sheila Rashid',
 'Pendleton',
 'Rox Brown',
 'Nike',
 'Comme des Garcons Homme',
 'PSNY']

In [9]:
collabo_lst_first_word = [collabo.split(' ')[0] for collabo in collabo_lst]
collabo_lst_first_word

['Clot',
 'Fragment',
 'Union',
 'Jayson',
 'J',
 'League',
 'Paris',
 'A',
 'Trophy',
 'Travis',
 'Maison',
 'Dior',
 'Nina',
 'Billie',
 'Off',
 'SoleFly',
 'Russell',
 'Supreme',
 'Levis',
 'Patta',
 'Aleali',
 'Social',
 'Ghetto',
 'Blue',
 'Lance',
 'SNS',
 'Facetasm',
 'DSM',
 'Kaws',
 'Olivia',
 'Titan',
 'Melody',
 'Anna',
 'Converse',
 'Vogue',
 'Serena',
 'Carmelo',
 'Carhartt',
 'Sheila',
 'Pendleton',
 'Rox',
 'Nike',
 'Comme',
 'PSNY']

In [ ]:
'Clot'
'Fragment'
'Union'
'Jayson'
'J'
'League'
'Paris'
'A'
'Trophy'
'Travis'
'Maison'
'Dior'
'Nina'
'Billie'
'Off'
'SoleFly'
'Russell'
'Supreme'
'Levis'
'Patta'
'Aleali'
'Social'
'Ghetto'
'Blue'
'Lance'
'SNS'
'Facetasm'
'DSM'
'Kaws'
'Olivia'
'Titan'
'Melody'
'Anna'
'Converse'
'Vogue'
'Serena'
'Carmelo'
'Carhartt'
'Sheila'
'Pendleton'
'Rox'
'Nike'
'Comme'
'PSNY'

In [10]:
df_collabo = pd.DataFrame(np.zeros((len(df), 44)), columns=collabo_lst, dtype=np.int64)
df_collabo

,Clot,Fragment,Union,Jayson Tatum,J Balvin,League of Legends,Paris Saint Germain,A Ma Maniere,Trophy Room,Travis Scott,...,Vogue,Serena Williams,Carmelo Anthony,Carhartt,Sheila Rashid,Pendleton,Rox Brown,Nike,Comme des Garcons Homme,PSNY
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df2 = pd.concat([df, df_collabo], axis=1)
df2

,_id,brand,prod_kr_name,rescent_price,model_no,release_date,colors,release_price,instant_buy_price,instant_sell_price,...,Vogue,Serena Williams,Carmelo Anthony,Carhartt,Sheila Rashid,Pendleton,Rox Brown,Nike,Comme des Garcons Homme,PSNY
0,Jordan 1 Low Vintage Grey,Jordan,조던 1 로우 빈티지 그레이,"200,000",553558-053,-,GREY/WHITE/CREAM,"129,000원","202,000","201,000",...,0,0,0,0,0,0,0,0,0,0
1,Jordan 1 x Travis Scott x Fragment Retro Low O...,Jordan,조던 1 x 트래비스 스캇 x 프라그먼트 레트로 로우 OG SP 밀리터리 블루,"1,555,000",DM7866-140,21/08/13,SAIL/BLACK/MILITARY BLUE,"189,000원","1,540,000","2,230,000",...,0,0,0,0,0,0,0,0,0,0
2,Jordan 1 Retro High OG Black Mocha,Jordan,조던 1 레트로 하이 OG 블랙 모카,"702,000",555088-105,20/11/13,SAIL/DARK MOCHA-BLACK-BLACK,"199,000원","600,000","818,000",...,0,0,0,0,0,0,0,0,0,0
3,Jordan 4 Retro White and Black,Jordan,조던 4 레트로 화이트 앤 블랙,"312,000",DH6927-111,22/05/23,WHITE/BLACK/NEUTRAL GREY,"249,000원","299,000","313,000",...,0,0,0,0,0,0,0,0,0,0
4,Jordan 1 Retro High OG Bleached Coral,Jordan,조던 1 레트로 하이 OG 블리치드 코랄,"244,000",555088-108,22/05/14,WHITE/BLACK/GREY FOG/BLEACHED CORAL,"209,000원","207,000","270,000",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,Jordan 1 Retro High OG SP Gina (Special Box),Jordan,조던 1 레트로 하이 OG SP 지나 (스페셜 박스),-,CD7071-001,19/05/25,BLACK/BLACK-WHITE-VARSITY RED,"$180 (약 234,600원)",-,-,...,0,0,0,0,0,0,0,0,0,0
3000,Jordan 13 Retro Low Quai 54,Jordan,조던 13 레트로 로우 콰이 54,-,810551-050,15/06/14,BLACK/DARK GREY-WHITE-CHROME,"$250 (약 325,200원)",-,-,...,0,0,0,0,0,0,0,0,0,0
3001,(GS) Jordan 11 Retro Heiress Velvet,Jordan,(GS) 조던 11 레트로 헤어리스 벨벳,"290,000",852625-650,16/12/18,NIGHT MAROON/METALLIC GOLD-NIGHT MAROON,"$220 (약 286,200원)","340,000","180,000",...,0,0,0,0,0,0,0,0,0,0
3002,Jordan 1 Retro High Flyknit Derek Jeter RE2PECT,Jordan,조던 1 레트로 하이 플라이니트 데릭 지터 RE2PECT,"350,000",AH7233-105,18/02/24,SAIL/METALLIC GOLD-MIDNIGHT NAVY,"$180 (약 234,100원)","380,000","150,000",...,0,0,0,0,0,0,0,0,0,0
3003,(GS) Jordan 1 Retro High Melo,Jordan,(GS) 조던 1 레트로 하이 멜로,"229,000",705300-026,14/12/20,BLACK/METALLIC GOLD-WHITE,"$110 (약 143,100원)","299,000",-,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df2['Clot'] = df2['collabo'].apply(lambda x: 1 if 'Clot' in x else 0)
df2['Fragment'] = df2['collabo'].apply(lambda x: 1 if 'Fragment' in x else 0)
df2['Union'] = df2['collabo'].apply(lambda x: 1 if 'Union' in x else 0)
df2['Jayson Tatum'] = df2['collabo'].apply(lambda x: 1 if 'Jayson' in x else 0)
df2['J Balvin'] = df2['collabo'].apply(lambda x: 1 if 'J' in x else 0)
df2['League of Legends'] = df2['collabo'].apply(lambda x: 1 if 'League' in x else 0)
df2['Paris Saint Germain'] = df2['collabo'].apply(lambda x: 1 if 'Paris' in x else 0)
df2['A Ma Maniere'] = df2['collabo'].apply(lambda x: 1 if 'A' in x else 0)
df2['Trophy Room'] = df2['collabo'].apply(lambda x: 1 if 'Trophy' in x else 0)
df2['Travis Scott'] = df2['collabo'].apply(lambda x: 1 if 'Travis' in x else 0)
df2['Maison Chateau Rouge'] = df2['collabo'].apply(lambda x: 1 if 'Maison' in x else 0)
df2['Dior'] = df2['collabo'].apply(lambda x: 1 if 'Dior' in x else 0)
df2['Nina Chanel Abney'] = df2['collabo'].apply(lambda x: 1 if 'Nina' in x else 0)
df2['Billie Eilish'] = df2['collabo'].apply(lambda x: 1 if 'Billie' in x else 0)
df2['Off White'] = df2['collabo'].apply(lambda x: 1 if 'Off' in x else 0)
df2['SoleFly'] = df2['collabo'].apply(lambda x: 1 if 'SoleFly' in x else 0)
df2['Russell Westbrook'] = df2['collabo'].apply(lambda x: 1 if 'Russell' in x else 0)
df2['Supreme'] = df2['collabo'].apply(lambda x: 1 if 'Supreme' in x else 0)
df2['Levis'] = df2['collabo'].apply(lambda x: 1 if 'Levis' in x else 0)
df2['Patta'] = df2['collabo'].apply(lambda x: 1 if 'Patta' in x else 0)
df2['Aleali May'] = df2['collabo'].apply(lambda x: 1 if 'Aleali' in x else 0)
df2['Social Status'] = df2['collabo'].apply(lambda x: 1 if 'Social' in x else 0)
df2['Ghetto Gastro'] = df2['collabo'].apply(lambda x: 1 if 'Ghetto' in x else 0)
df2['Blue The Great'] = df2['collabo'].apply(lambda x: 1 if 'Blue' in x else 0)
df2['Lance Mountain'] = df2['collabo'].apply(lambda x: 1 if 'Lance' in x else 0)
df2['SNS'] = df2['collabo'].apply(lambda x: 1 if 'SNS' in x else 0)
df2['Facetasm'] = df2['collabo'].apply(lambda x: 1 if 'Facetasm' in x else 0)
df2['DSM'] = df2['collabo'].apply(lambda x: 1 if 'DSM' in x else 0)
df2['Kaws'] = df2['collabo'].apply(lambda x: 1 if 'Kaws' in x else 0)
df2['Olivia Kim'] = df2['collabo'].apply(lambda x: 1 if 'Olivia' in x else 0)
df2['Titan'] = df2['collabo'].apply(lambda x: 1 if 'Titan' in x else 0)
df2['Melody Ehsani'] = df2['collabo'].apply(lambda x: 1 if 'Melody' in x else 0)
df2['Anna Wintour'] = df2['collabo'].apply(lambda x: 1 if 'Anna' in x else 0)
df2['Converse'] = df2['collabo'].apply(lambda x: 1 if 'Converse' in x else 0)
df2['Vogue'] = df2['collabo'].apply(lambda x: 1 if 'Vogue' in x else 0)
df2['Serena Williams'] = df2['collabo'].apply(lambda x: 1 if 'Serena' in x else 0)
df2['Carmelo Anthony'] = df2['collabo'].apply(lambda x: 1 if 'Carmelo' in x else 0)
df2['Carhartt'] = df2['collabo'].apply(lambda x: 1 if 'Carhartt' in x else 0)
df2['Sheila Rashid'] = df2['collabo'].apply(lambda x: 1 if 'Sheila' in x else 0)
df2['Pendleton'] = df2['collabo'].apply(lambda x: 1 if 'Pendleton' in x else 0)
df2['Rox Brown'] = df2['collabo'].apply(lambda x: 1 if 'Rox' in x else 0)
df2['Nike'] = df2['collabo'].apply(lambda x: 1 if 'Nike' in x else 0)
df2['Comme des Garcons Homme'] = df2['collabo'].apply(lambda x: 1 if 'Comme' in x else 0)
df2['PSNY'] = df2['collabo'].apply(lambda x: 1 if 'PSNY' in x else 0)

In [13]:
df2[df2['collabo'] != ''].iloc[:50, 11:30]

,collabo,Clot,Fragment,Union,Jayson Tatum,J Balvin,League of Legends,Paris Saint Germain,A Ma Maniere,Trophy Room,Travis Scott,Maison Chateau Rouge,Dior,Nina Chanel Abney,Billie Eilish,Off White,SoleFly,Russell Westbrook,Supreme
1,"Travis,Fragment",0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
19,A,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
39,Travis,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
56,Travis,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
68,Travis,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
84,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
99,J,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
102,Maison,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
119,Maison,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
127,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
130,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
131,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133,Fragment,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
135,Travis,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
137,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
138,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
141,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
144,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
148,Trophy,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
150,Dior,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
158,Nina,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
165,Fragment,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
209,League,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
221,Billie,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
276,A,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
287,Clot,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
289,"Travis,Fragment",0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
293,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
303,A,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
307,SoleFly,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
311,Paris,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
315,Billie,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
317,A,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
324,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
327,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
343,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
344,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
355,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
358,Aleali,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
372,Russell,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
379,A,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
410,Dior,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
435,Off,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
445,Travis,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
460,Paris,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
477,Maison,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
480,Clot,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
507,Maison,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
516,Union,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
561,Lance,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
df2.iloc[150:200]

,_id,brand,prod_kr_name,rescent_price,model_no,release_date,colors,release_price,instant_buy_price,instant_sell_price,...,Vogue,Serena Williams,Carmelo Anthony,Carhartt,Sheila Rashid,Pendleton,Rox Brown,Nike,Comme des Garcons Homme,PSNY
150,Jordan 1 x Dior Low OG,Jordan,조던 1 x 디올 로우 OG,"8,150,000",CN8608-002,20/07/08,WOLF GREY/SAIL-PHOTON DUST-WHITE,"2,700,000원","7,900,000","8,060,000",...,0,0,0,0,0,0,0,0,0,0
151,Jordan 4 Retro Cool Grey 2019,Jordan,조던 4 레트로 쿨 그레이 2019,"400,000",308497-007,19/08/02,COOL GREY/CHROME-DARK CHARCOAL-VARSITY MAIZE,"$190 (약 247,700원)","410,000","450,000",...,0,0,0,0,0,0,0,0,0,0
152,Jordan 4 Golf Black Cat,Jordan,조던 4 골프 블랙 캣,"465,000",CU9981-001,21/12/01,BLACK/CEMENT GREY,"289,000원","229,000","326,000",...,0,0,0,0,0,0,0,0,0,0
153,Jordan 1 Retro High OG Reverse Shattered Backb...,Jordan,조던 1 레트로 하이 OG 리버스 쉐터드 백보드,"1,300,000",555088-113,16/10/09,SAIL/STARFISH-BLACK,"$160 (약 208,600원)","1,489,000","1,500,000",...,0,0,0,0,0,0,0,0,0,0
154,Jordan 11 Retro Legend Blue 2014,Jordan,조던 11 레트로 레전드 블루 2014,"430,000",378037-117,14/12/21,WHITE/BLACK-LEGEND BLUE,"$200 (약 260,700원)","380,000","305,000",...,0,0,0,0,0,0,0,0,0,0
155,Jordan 11 Retro Low Bred,Jordan,조던 11 레트로 로우 브레드,"460,000",528895-012,15/05/24,BLACK/TRUE RED-WHITE,"$170 (약 221,600원)","410,000","420,000",...,0,0,0,0,0,0,0,0,0,0
156,Jordan 13 Retro He Got Game 2018,Jordan,조던 13 레트로 히갓게임 2018,"420,000",414571-104,18/08/05,WHITE/TRUE RED-BLACK,"$190 (약 247,700원)","430,000","550,000",...,0,0,0,0,0,0,0,0,0,0
157,Jordan 4 Retro Black Cat 2020,Jordan,조던 4 레트로 블랙 캣 2020,"700,000",CU1110-010,20/01/31,BLACK/BLACK-LIGHT GRAPHITE,"229,000원","700,000","710,000",...,0,0,0,0,0,0,0,0,0,0
158,(W) Jordan 2 x Nina Chanel Abney Retro Low SE ...,Jordan,(W) 조던 2 x 니나 샤넬 애브니 레트로 로우 SE 화이트 앤 말라카이트,"389,000",DQ0560-160,22/07/08,WHITE/MALACHITE-NEUTRAL GREY-SAIL,"269,000원","375,000","200,000",...,0,0,0,0,0,0,0,0,0,0
159,(GS) Jordan 1 Retro High Obsidian UNC,Jordan,(GS) 조던 1 레트로 하이 옵시디언 UNC,"540,000",575441-140,19/09/01,SAIL/OBSIDIAN-UNIVERSITY BLUE,"$120 (약 156,400원)","599,000","520,000",...,0,0,0,0,0,0,0,0,0,0
160,Jordan 1 Retro High Fearless UNC Chicago,Jordan,조던 1 레트로 하이 피어리스 UNC 시카고,"305,000",CK5666-100,19/11/03,WHITE/UNIVERSITY BLUE-VARSITY RED-BLACK,"$160 (약 208,600원)","329,000","350,000",...,0,0,0,0,0,0,0,0,0,0
161,Jordan 1 Mid Black Fire Red,Jordan,조던 1 미드 블랙 파이어 레드,"146,000",554724-079,22/06/16,BLACK/FIRE RED/WHITE,"149,000원","142,000","150,000",...,0,0,0,0,0,0,0,0,0,0
162,Jordan 1 Low SE Light Curry,Jordan,조던 1 로우 SE 라이트 커리,"145,000",DH6931-102,22/02/07,WHITE/MEDIUM OLIVE/LIGHT CURRY/WHITE,"139,000원","140,000","143,000",...,0,0,0,0,0,0,0,0,0,0
163,Jordan 4 Retro Motorsports 2017,Jordan,조던 4 레트로 모터스포츠 2017,"450,000",308497-117,17/03/27,WHITE/VARSITY BLUE-BLACK,"$190 (약 247,700원)","499,000","280,000",...,0,0,0,0,0,0,0,0,0,0
164,Jordan 1.5 Retro Reverse Fragment,Jordan,조던 1.5 레트로 리버스 프라그먼트,"430,000",768861-106,15/10/18,WHITE/BLACK-SOAR,"$150 (약 195,500원)","359,000","300,000",...,0,0,0,0,0,0,0,0,0,0
165,Jordan 1 x Fragment Retro High OG,Jordan,조던 1 x 프라그먼트 레트로 하이 OG,"3,800,000",716371-040,14/12/28,BLACK/SPORT BLUE-WHITE,"$185 (약 241,200원)","4,500,000","5,000,000",...,0,0,0,0,0,0,0,0,0,0
166,(W) Jordan 1 Low Light Madder Root,Jordan,(W) 조던 1 로우 라이트 매더 루트,"142,000",DC0774-800,22/04/11,LIGHT MADDER ROOT/DARK TEAL GREEN,"129,000원","144,000","153,000",...,0,0,0,0,0,0,0,0,0,0
167,(W) Jordan 1 Retro High Satin Red,Jordan,(W) 조던 1 레트로 하이 사틴 레드,"308,000",CD0461-601,20/08/06,GYM RED/WHITE-BLACK,"189,000원","230,000","300,000",...,0,0,0,0,0,0,0,0,0,0
168,Jordan 6 Retro DMP 2020,Jordan,조던 6 레트로 DMP 2020,"190,000",CT4954-007,20/03/30,BLACK/METALLIC GOLD,"239,000원","220,000","219,000",...,0,0,0,0,0,0,0,0,0,0
169,(GS) Jordan 4 Retro Tour Yellow,Jordan,(GS) 조던 4 레트로 투어 옐로우,"190,000",408452-700,21/08/28,TOUR YELLOW/WHITE/DARK BLUE GREY,"169,000원","180,000","206,000",...,0,0,0,0,0,0,0,0,0,0
170,Jordan 17 Retro Copper 2016,Jordan,조던 17 레트로 플러스 카퍼 2016,"299,000",832816-122,16/04/10,COPPER-BLACK-WHITE,"$250 (약 325,900원)","900,000","230,000",...,0,0,0,0,0,0,0,0,0,0
171,Jordan 1 Retro High OG Electro Orange,Jordan,조던 1 레트로 하이 OG 일렉트로 오렌지,"188,000",555088-180,21/07/17,WHITE/ELECTRO ORANGE-BLACK,"199,000원","173,000","199,000",...,0,0,0,0,0,0,0,0,0,0
172,Jordan 13 Retro Bred 2017,Jordan,조던 13 레트로 브레드 2017,"295,000",414571-004,17/08/20,BLACK/TRUE RED-WHITE,"$190 (약 247,700원)","310,000","250,000",...,0,0,0,0,0,0,0,0,0,0
173,Jordan 1 Low Gym Red White,Jordan,조던 1 로우 짐레드 화이트,"295,000",553558-611,20/03/01,GYM RED/GYM RED-WHITE,"119,000원","320,000","340,000",...,0,0,0,0,0,0,0,0,0,0
174,Jordan 1 Low Varsity Red,Jordan,조던 1 로우 바시티 레드,"180,000",553558-606,20/06/30,GYM RED/BLACK-GYM RED-WHITE,"119,000원","158,000","180,000",...,0,0,0,0,0,0,0,0,0,0
175,Jordan 1 Low Green Toe,Jordan,조던 1 로우 그린토,"289,000",553558-371,21/09/30,GREEN/BLACK-WHITE-GOLD,"119,000원","239,000","257,000",...,0,0,0,0,0,0,0,0,0,0
176,Jordan 1 Mid SE Craft White and Phantom,Jordan,조던 1 미드 SE 크래프트 화이트 앤 팬텀,"113,000",DM9652-100,22/06/29,WHITE/MONTREAL GREY/PHANTOM,"159,000원","120,000","115,000",...,0,0,0,0,0,0,0,0,0,0
177,(GS) Jordan 1 Retro High OG Shadow 2.0,Jordan,(GS) 조던 1 하이 레트로 하이 OG 쉐도우 2.0,"280,000",575441-035,21/05/15,BLACK/LIGHT SMOKE GREY-WHITE,"139,000원","240,000","280,000",...,0,0,0,0,0,0,0,0,0,0
178,(GS) Jordan 4 Retro University Blue,Jordan,(GS) 조던 4 레트로 유니버시티 블루,"280,000",408452-400,21/04/28,UNIVERSITY BLUE/TECH GREY-WHITE-BLACK,"169,000원","228,000","280,000",...,0,0,0,0,0,0,0,0,0,0
179,(GS) Jordan 1 Mid White Gym Red Black,Jordan,(GS) 조던 1 미드 화이트 짐레드 블랙,"270,000",554725-173,20/06/19,WHITE/GYM RED/BLACK,"109,000원","232,000","250,000",...,0,0,0,0,0,0,0,0,0,0
180,Jordan 4 Retro SE Deep Ocean,Jordan,조던 4 레트로 SE 딥 오션,"270,000",CW0898-400,20/12/05,DEEP OCEAN/SAIL-CEMENT GREY-FIRE RED,"€225 (약 301,000원)","345,000","340,000",...,0,0,0,0,0,0,0,0,0,0
181,Jordan 1 Low SE White Black Tie-Dye,Jordan,조던 1 로우 SE 화이트 블랙 타이다이,"170,000",DM1199-100,22/05/15,WHITE/MINT FOAM-BORDEAUX,"￡110 (약 171,800원)","168,000","190,000",...,0,0,0,0,0,0,0,0,0,0
182,Jordan 1 Low Pollen,Jordan,조던 1 로우 폴른,"269,000",553558-171,21/07/15,WHITE/POLLEN,"119,000원","189,000","230,000",...,0,0,0,0,0,0,0,0,0,0
183,Jordan 1 Mid Triple White,Jordan,조던 1 미드 트리플 화이트,"168,000",554724-130,20/04/09,WHITE/WHITE/WHITE,"139,000원","145,000","143,000",...,0,0,0,0,0,0,0,0,0,0
184,(W) Jordan 1 Low OG Neutral Grey 2021,Jordan,(W) 조던 1 로우 OG 뉴트럴 그레이 2021,"263,000",CZ0775-100,21/06/17,WHITE/WHITE-NEUTRAL GREY,"159,000원","209,000","230,000",...,0,0,0,0,0,0,0,0,0,0
185,Jordan 11 Retro Low Closing Ceremony,Jordan,조던 11 레트로 로우 클로징 세레모니,"269,000",528895-103,16/08/28,WHITE/METALLIC GOLD COIN-BLACK,"$170 (약 221,600원)","259,000","243,000",...,0,0,0,0,0,0,0,0,0,0
186,Jordan 1 Retro High OG Volt,Jordan,조던 1 레트로 하이 OG 볼트,"164,000",555088-702,22/06/11,VOLT/BLACK/SAIL,"209,000원","162,000","200,000",...,0,0,0,0,0,0,0,0,0,0
187,(GS) Jordan 1 Retro High OG Hyper Royal,Jordan,(GS) 조던 1 레트로 하이 OG 하이퍼 로얄,"260,000",575441-402,21/04/14,HYPER ROYAL/LIGHT SMOKE GREY/WHITE,"139,000원","285,000","311,000",...,0,0,0,0,0,0,0,0,0,0
188,(GS) Jordan 1 Low Light Arctic Pink,Jordan,(GS) 조던 1 로우 라이트 아크틱 핑크,"258,000",553560-800,21/03/24,LIGHT ARCTIC PINK/WHITE-BLACK,"99,000원","212,000","240,000",...,0,0,0,0,0,0,0,0,0,0
189,Jordan 1 Mid Racer Blue,Jordan,조던 1 미드 레이서 블루,"255,000",554724-140,21/06/10,WHITE/RACER BLUE/BLACK,"139,000원","217,000","221,000",...,0,0,0,0,0,0,0,0,0,0
190,Jordan 4 Golf Bred,Jordan,조던 4 골프 브레드,"250,000",CU9981-002,21/12/19,BLACK/FIRE RED-CEMENT GREY-WHITE,"289,000원","271,000","270,000",...,0,0,0,0,0,0,0,0,0,0
191,Jordan 1 Mid SE Pine Green Light Smoke Grey,Jordan,조던 1 미드 SE 파인 그린 라이트 스모크 그레이,"250,000",DC7294-103,21/12/07,WHITE/PINE GREEN-LIGHT SMOKE GREY,"159,000원","250,000","245,000",...,0,0,0,0,0,0,0,0,0,0
192,Jordan 1 Low SE ASW Black,Jordan,조던 1 로우 SE ASW 블랙,"250,000",DD1650-001,21/03/10,BLACK/WHITE,"129,000원","200,000","170,000",...,0,0,0,0,0,0,0,0,0,0
193,(W) Jordan 1 Low Citron Tint,Jordan,(W) 조던 1 로우 시트론 틴트,"110,000",DC0774-007,22/06/14,PURE PLATINUM/WHITE/CITRON TINT,"129,000원","120,000","145,000",...,0,0,0,0,0,0,0,0,0,0
194,Jordan 1 Mid Shadow,Jordan,조던 1 미드 쉐도우,"155,000",554724-096,22/02/15,BLACK/PARTICLE GREY/WHITE/GYM RED,"139,000원","130,000","150,000",...,0,0,0,0,0,0,0,0,0,0
195,Jordan 1 Low OG Neutral Grey 2021,Jordan,조던 1 로우 OG 뉴트럴 그레이 2021,"275,000",CZ0790-100,21/06/17,WHITE/WHITE-NEUTRAL GREY,"159,000원","231,000","250,000",...,0,0,0,0,0,0,0,0,0,0
196,Jordan 3 Retro Pine Green,Jordan,조던 3 레트로 파인 그린,"245,000",CT8532-030,21/10/23,BLACK/PINE GREEN-CEMENT GREY-WHITE,"229,000원","209,000","200,000",...,0,0,0,0,0,0,0,0,0,0
197,(W) Jordan 1 Elevate Low SE Bred,Jordan,(W) 조던 1 엘리베이트 로우 SE 브레드,"142,000",DQ1823-006,22/02/19,BLACK/GYM RED-SAIL,"169,000원","129,000","141,000",...,0,0,0,0,0,0,0,0,0,0
198,(GS) Jordan 1 Retro High OG Pollen,Jordan,(GS) 조던 1 레트로 하이 OG 폴른,"172,000",575441-701,21/08/27,POLLEN/BLACK-WHITE,"139,000원","134,000","145,000",...,0,0,0,0,0,0,0,0,0,0
199,Jordan 1 Zoom Air CMFT Stadium Green,Jordan,조던 1 줌 에어 컴포트 스타디움 그린,"240,000",CT0978-300,21/03/26,STADIUM GREEN/BLACK-WHITE-GHOST GREEN,"$150 (약 195,500원)","213,000","220,000",...,0,0,0,0,0,0,0,0,0,0

In [15]:
df2.to_csv('collabo.csv', index=False)